// UI Components exports
export { ArrowAnimated } from "./ArrowAnimated"
export { default as Benefits } from "./Benefits"
export { default as CodeExample } from "./CodeExample"
export { default as CodeExampleTabs } from "./CodeExampleTabs"
export { default as Cta } from "./Cta"
export { Faqs } from "./Faqs"
export { default as Features } from "./Features"
export { default as Footer } from "./Footer"
export { GlobalDatabase } from "./GlobalDatabase"
export { default as Hero } from "./Hero"
export { default as HeroImage } from "./HeroImage"
export { default as InstaxImage } from "./InstaxImage"
export { default as LogoCloud } from "./LogoCloud"
export { default as Logos } from "./Logos"
export { Navigation } from "./Navbar"
export { default as TeamGallery } from "./TeamGallery"
export { default as Testimonial } from "./Testimonial"
export { default as ThemedImage } from "./ThemedImage"
