export enum ErrorCode {
  // Authentication Errors (401)
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  MFA_REQUIRED = 'MFA_REQUIRED',
  INVALID_MFA_TOKEN = 'INVALID_MFA_TOKEN',

  // Authorization Errors (403)
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  CANNOT_GRANT_PERMISSION = 'CANNOT_GRANT_PERMISSION',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  ROLE_HIERARCHY_VIOLATION = 'ROLE_HIERARCHY_VIOLATION',
  OWNER_DELETION_FORBIDDEN = 'OWNER_DELETION_FORBIDDEN',

  // Validation Errors (400)
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_INPUT = 'INVALID_INPUT',
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  PASSWORD_IN_HISTORY = 'PASSWORD_IN_HISTORY',
  DUPLICATE_ENTITY = 'DUPLICATE_ENTITY',

  // Resource Errors (404)
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',

  // Rate Limiting (429)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Server Errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  CACHE_ERROR = 'CACHE_ERROR',

  // Service Unavailable (503)
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  CACHE_UNAVAILABLE = 'CACHE_UNAVAILABLE',
}
