/**
 * Complete Auth GraphQL Queries
 * Re-exports all auth query operations needed by auth managers
 */

// Re-export all queries from auth.ts
export {
  // Authentication Queries
  REQUIRES_MFA_QUERY,
  ME_QUERY,
  // MFA Queries
  MFA_STATUS_QUERY,
  IS_MFA_ENABLED_QUERY,
  // Permission Queries
  GET_PERMISSIONS_QUERY,
  MY_PERMISSIONS_QUERY,
  GET_ROLES_QUERY,
  GET_ROLE_PERMISSIONS_QUERY,
  HAS_PERMISSION_QUERY,
  GET_ALL_PERMISSIONS_QUERY,
  GET_DETAILED_PERMISSIONS_QUERY,
  CHECK_PERMISSION_QUERY,
  GET_AVAILABLE_PERMISSIONS_QUERY,
  GET_USER_PERMISSIONS_QUERY,
  // Tier Queries
  GET_MY_TIER_QUERY,
  GET_USER_FEATURES_QUERY,
  GET_UPGRADE_RECOMMENDATIONS_QUERY,
  // Feature Access Queries
  BASIC_FEATURE_QUERY,
  SMALL_TIER_FEATURE_QUERY,
  MEDIUM_TIER_FEATURE_QUERY,
  ENTERPRISE_FEATURE_QUERY,
  ADVANCED_REPORTS_QUERY,
  MULTI_LOCATION_DATA_QUERY,
  // Session Queries
  GET_ACTIVE_SESSIONS_QUERY,
  GET_DEVICE_SESSIONS_QUERY,
  GET_TRUSTED_DEVICES_QUERY,
  // Onboarding Queries
  GET_ONBOARDING_STATUS_QUERY,
  // Subscription Queries
  GET_SUBSCRIPTION_STATUS_QUERY,
  // Security Queries
  GET_SECURITY_SETTINGS_QUERY,
  GET_AUDIT_LOGS_QUERY,
  GET_IP_RESTRICTIONS_QUERY,
  GET_TIME_BASED_ACCESS_QUERY,
} from './auth';
